/*
 * colors.h - a bunch of common colors in standard.pal
 *
 * DESCRIPTION
 * These are the same in standard.pal as the first 16 VGA colors
 *
 * USAGE
 *
 * NOTES
 *
 * REVISION HISTORY
 * Date         Reason
 * 13 Jul 95    Initial Coding
 *
 */

#ifndef _COLORS_H_
#define _COLORS_H_

#ifdef __cplusplus
extern "C" {
#endif


#define BLACK           0
#define WHITE           15
#define LT_GREY         7
#define DK_GREY         8
#define BLUE            1
#define RED             4
#define GREEN           2
#define LT_BLUE         9
#define LT_RED          12
#define LT_GREEN        10
#define BROWN           6
#define YELLOW          14

#ifdef __cplusplus
}
#endif

#endif
