//อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
//                                   GDM
//                 BWSB/32 Music and Sound Engine Source Code
//                   Copyright (c) 1993-97, Edward Schlunder
// 
//                Written by Edward Schlunder/OverThrowMachine
//อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
#include <stdio.h>

void _musUpdateGDM(MusicEngine& mus);
int _musLoadGDM(MusicEngine& mus, FILE *fpFile);
int _musSaveGDM(MusicEngine& mus, FILE *fpFile);
