extern void cdecl MainMenu(char Row, char Col);
extern void cdecl SoundCardMenu(char Row, char Col);
extern void cdecl BaseioMenu(char Row, char Col);
extern void cdecl IRQMenu(char Row, char Col);
extern void cdecl DMAMenu(char Row, char Col);
extern void cdecl QualityMenu(char Row, char Col);
extern void cdecl TestScreen(char Row, char Col);
extern void cdecl ErrorScreen(char Row, char Col);
